### ISSUE TITLE
Build error on Raspberry

### ISSUE THREAD

**Issue by etienne-gauvin** [petrkutalek/png2pos#1]
Hi,
I'm trying to build _png2pos_ on a Raspberry running on xbian. There is an error with syscalls/mmap and I don't know how to solve it, can you please help me ?

```
root@xbian:/home/xbian/png2pos# make
CC              png2pos.o
In file included from seccomp.h:10:0,
                 from png2pos.c:18:
seccomp.h:65:41: error: ‘__NR_mmap’ undeclared here (not in a function)
     BPF_JUMP(BPF_JMP + BPF_JEQ + BPF_K, __NR_##name, 0, 1), \
                                         ^
seccomp.h:83:5: note: in expansion of macro ‘ALLOW_SYSCALL’
     ALLOW_SYSCALL(mmap),
     ^~~~~~~~~~~~~
In file included from png2pos.c:18:0:
seccomp.h:83:5: warning: missing initializer for field ‘k’ of ‘struct sock_filter’ [-Wmissing-field-initializers]
In file included from seccomp.h:10:0,
                 from png2pos.c:18:
/usr/include/linux/filter.h:28:8: note: ‘k’ declared here
  __u32 k;      /* Generic multiuse field */
        ^
Makefile:54: recipe for target 'png2pos.o' failed
make: *** [png2pos.o] Error 1
```

(for a moment I thought I solved it by adding "2" to "mmap" on line 83 in seccomp.c but after that, even if the build works without error, everytime I try to launch "png2pos" it fails with a "Bad system call")

Thank you by advance for your answer.

**Comment by petrkutalek** [comment]
Thanks, I will check that. Till then you can build png2pos without seccomp: just add `-DNOSECCOMP` to `CFLAGS` in Makefile

**Comment by etienne-gauvin** [comment]
Thanks, I can now build without error.
It will be enough for my usage, as the Raspberry won't be connected to any network.

(I have an other problem now, but I'll open a different GitHub issue...)
