### ISSUE TITLE
Direct send of file to COM port prints binary

### ISSUE THREAD

**Issue by kewilson** [petrkutalek/png2pos#13]
Linux host:  Compile and run -> ./png2pos -c -p ./samplereceipt.png > out.txt

Copy out.txt file to Windows host
Send file to printer: NCR 7167 Printer via COM port on Windows host

copy out.txt \\.\COM8 /b 

Prints what I believe to the file contents instead of the esc/pos wrapped contents of the PNG image.

What might I be doing incorrectly?

**Comment by petrkutalek** [comment]
Hi, please attach an archive containing source PNG and produced TXT files.

**Comment by kewilson** [comment]
The templatereceipt.png is the primary interest. The samplereceipt.png is just along for the ride but it does emit a message that it is too wide which is to be expected. Thanks for looking at these, much appreciated.
[png2possamples.zip](https://github.com/petrkutalek/png2pos/files/1521923/png2possamples.zip)

**Comment by petrkutalek** [comment]
`png2pos` seems OK, I do not use Windows, nevertheless check this [print.cmd](https://github.com/petrkutalek/png2pos/blob/windows/win/print.cmd) file from windows branch, [explanation here](https://mike42.me/blog/2015-04-getting-a-usb-receipt-printer-working-on-windows). I have no idea how to copy binary file to COM port in Windows.
