### ISSUE TITLE
How to test without printer?

### ISSUE THREAD

**Issue by sam-lex** [petrkutalek/png2pos#14]
Hello, I just tried to install on mac, at the end of Install, there's an error code: 64.
```
home:png2pos sam$ make CC=clang
CC              png2pos.o
CC              deps/lodepng/lodepng.o
LD              png2pos
clang: warning: argument unused during compilation: '-pie'
home:png2pos sam$ sudo make install
GZIP            png2pos.1.gz
mkdir -p /usr/local/bin /usr/local/share/man/man1
install -m755 png2pos /usr/local/bin
install -m644 png2pos.1.gz /usr/local/share/man/man1
install -m644 -T png2pos.complete /etc/bash_completion.d/png2pos
install: illegal option -- T
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make: *** [install] Error 64
```
Is it something I should be concerned with? it seems to have installed though, I don't have a printer with me. So is there a way to test this?

I tried doing: `png2pos -c -p input.png > test.png`

it generated a `test.png`, but can't visualize it. So I'm not sure if it generated correctly.

I tried using an image like this one: (384x500)
https://www.wpclipart.com/office/presentation/presentation_woman_pointing_to_results_chart.png

**Comment by petrkutalek** [comment]
Hi @sam-lex, as for clang `-pie` warning that is no major problem. In #14 I have fixed install incompatibility with mac. In your case `png2pos` installed correctly except bash completion file. Nevertheless it should work all right.

Just to be sure you understand `png2pos` correctly: it does not generate PNG files, it generates binary ESC/POS files – printing commands, bitmaps etc.
