### ISSUE TITLE
How to compile/install on windows?

### ISSUE THREAD

**Issue by sam-lex** [petrkutalek/png2pos#15]
Hello, how can I install this on windows 7 - 32bits?
I've tried gnuwin32:
```
process_begin: CreateProcess(NULL, uname -s, ...) failed.
'printf' is not recognized as an internal or external command,
operable program or batch file.
make: *** [png2pos.o] Error 1
```
Then, tried with MinGW:
`mingw32-make`,  
`mingw32-make -f Makefile`  
gives the same output.
and also:
```
> mingw32-make -f Makefile strip CC=gcc
process_begin: CreateProcess(NULL, uname -s, ...) failed.
mingw32-make: *** No rule to make target 'strip'. Stop.
```

when downloading MinGW, I checked base version, gcc and cpp. So I don't knkow why it gives error on `printf`.

path: `C:\MinGW\bin;C:\MinGW\mingw32\bin`  
I noticed the `mingw32` after, so I added it to path, and tested the commands above again. It gave same outputs.

Thanks for your time.

**Comment by petrkutalek** [comment]
Some time ago I have created [`windows` branch](https://github.com/petrkutalek/png2pos/tree/windows). It includes some files that may be helpful with mingw. Nevertheless I do not support Windows anymore.
