### ISSUE TITLE
Printer doesn't understand the POS/ESC code from png2pos

### ISSUE THREAD

**Issue by etienne-gauvin** [petrkutalek/png2pos#2]
Hi again,

I can't print output from _png2pos_ on my little ZJ-5802LD. It looks like there is something the printer doesn't understand in the ESC/POS header, and it simply prints the binary data as text (so, giberish).

It is a pure B/W image already dithered. I've set PNG2POS_PRINTER_MAX_WIDTH to 384.
```sh
png2pos ./test.png > /dev/usb/lp0
```

I tried to print it with _png2escpos_ and the image was correctly printed (but I want to use png2pos for the automatic dithering functionnality).

So, I tried to understand and compare ESC/POS code output from both _png2pos_ and _png2escpos_: 

**First lines of output from png2pos:**
```
1B 40 1D 38 4C 0A 10 00 00 30 70 30 01 01 31 00
02 40 00 00 00 80 88 88 88 88 A8 AA AA AA AA AA
AA AA AA AA AA AA AA AA AA AA AA EA EE EE EE EE
FE FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
```
From what I understood by reading docs online, `1D 40` is an initialization sequence, and then `1D 38 4C` is supposed to... launch a graphic process with parameters `p1 p2 p3 p4 m fn`? I'm sorry but I don't understand what it does with that.

**First lines of output from png2escpos:**
```
1D 76 30 00 30 00 40 00 00 00 80 88 88 88 88 A8
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA
EA EE EE EE EE FE FF FF FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF 00 00 00 00 00 00 00 00
```
From what I can see, the two outputs are the same from `40 00 00 00 80 ...`. The header from _png2escpos_ is much shorter, and starts directly with a command `1D 76` to "Print raster bit images".

Is my printer too stupid to understand the header from _png2pos_? Do you have an idea of how I can solve this by still using _png2pos_?

Thank you by advance for your time and your answer.

**Comment by petrkutalek** [comment]
png2pos utilizes `GS 8 L` (Function 112) command for printing (`1D 38 .. 00 02 40 00`):
```
1B 40 1D 38 4C 0A 10 00 00 30 70 30 01 01 31 00
02 40 00 00 00 80 88 88 88 88 A8 AA AA AA AA AA
```
png2escpos `GS v 0` EPSON documents state: _This command is supported by only some of the printer models and will not be supported by future models. It is recommended to use graphics function `GS ( L` and `GS 8 L` (<Function 50> and <Function 112>)_.
In both cases a raster data begins by `00 00 80 88 88 88 88`. 

I am not sure I want to support this command, however you could change it yourself:

```
const unsigned char ESC_STORE[8] = {
    /* GS v 0, Print raster bit image, p. 268 */
    0x1d, 0x76, 0x30,
    /* m */
    0x00,
    /* xl, xh, number of dots in the horizontal direction */
    canvas_w & 0xff, canvas_w >> 8 & 0xff,
    /* yl, yh, number of dots in the vertical direction */
    k & 0xff, k >> 8 & 0xff
};
```
PNG2POS_PRINTER_MAX_WIDTH=384
PNG2POS_GS8L_MAX_Y=5

and maybe also remove init, flush, cut and other sequences…
