### ISSUE TITLE
Image output is very contrasted 

### ISSUE THREAD

**Issue by benoitguigal** [petrkutalek/png2pos#2]
Hello petrkutalek,
Thank you for open sourcing your code !  
I maintain [this library](https://github.com/benoitguigal/python-epson-printer) that also allows to print large images to Epson printer.
I tried to print an image on my TM-T20 using the command 'png2pos -c -r /tmp/*.png > /dev/usb/lp0 ' but I find the picture too contrasted. It does not seem to reproduce the B/W dithered version of the documentation. See image below : 
![lena_tm_t20](https://cloud.githubusercontent.com/assets/2269165/6852192/6499a56e-d3e3-11e4-8603-385b7df06634.jpg)
Is that the expected result ? Should I tune some parameter  ? 

Thanks 

Benoît

**Comment by petrkutalek** [comment]
Hi @benoitguigal — try to use ```-p``` switch to apply dithering.

**Comment by benoitguigal** [comment]
![img_1931](https://cloud.githubusercontent.com/assets/2269165/6853491/cec4a51c-d3eb-11e4-9cda-ef8215467e7c.JPG)
It works like a charm thank you !!
