### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by XieZhiFa** [petrkutalek/png2pos#3]
make
CC              png2pos.o
cc1: error: unrecognized command line option "-ftree-slp-vectorize"
cc1: error: unrecognized command line option "-fstack-protector-strong"
make: *** [png2pos.o] Error 1

**Comment by petrkutalek** [comment]
use `gcc` or disable those gcc options on [line 4 of Makefile](https://github.com/petrkutalek/png2pos/blob/master/Makefile#L4)
