### ISSUE TITLE
Bad system call

### ISSUE THREAD

**Issue by jazzyjube** [petrkutalek/png2pos#4]
Hi ! 

First, thank you for the amazing work :)

I have a problem with the following shell command :
png2pos -c -p /tmp/img.png > /dev/usb/lp0
Results with : 
"Bad system call" (I translated it from the french 'Appel système erroné')

After make/install png2pos, I had to add my user to the lp group then reboot because of permission problems. Then I got the error that I mentioned before.

Here is my configuration : 
Raspery Pi 3b+
Printer : Epson TM T20II
OS : Raspbian GNU/Linux 9

Thanks for your help !

**Comment by petrkutalek** [comment]
Hi, thank you. Please, could you check if current git version works for you?
