### ISSUE TITLE
Image is always aligned right on TM-T20 

### ISSUE THREAD

**Issue by benoitguigal** [petrkutalek/png2pos#5]
No matter what value is given to the -a argument, my image is always aligned right.

**Comment by petrkutalek** [comment]
Well, I do not have an access to TM-T20. Nevertheless, according to documentation it should support ```GS L``` command. Please note, TM-T20 is high density printer, i.e. it has resolution 203 dpi = 576 dots per line. You have to set ```PNG2POS_PRINTER_MAX_WIDTH``` shell variable as described in man page:
```bash
export PNG2POS_PRINTER_MAX_WIDTH=576
png2pos -a C …
```

@benoitguigal would you be so kind as to provide me with some sample image, output produced by png2pos (e.g. ```-a C```, centre aligned) and photo of created output? I would appreciate that.

**Comment by benoitguigal** [comment]
Indeed I had to export the environment variable. I very appreciate your help ! Example of result below
![img_2672](https://cloud.githubusercontent.com/assets/2269165/10965514/ca9743c4-83ad-11e5-8f9f-a70651ed6045.JPG)
