### ISSUE TITLE
Accept input files as base64 string

### ISSUE THREAD

**Issue by benoitguigal** [petrkutalek/png2pos#6]
I have an application using png2pos and I receive my png file encoded as a base64 string. Would it possible to accept input files encoded as base64 string ? I would like to handle everything in-memory and do not have to save my image to disk.
I recognize this is a edge case, so if you do not want to include this in your library I would appreciate some guidance on how to implement this (I am a total newbie in C). 
Thanks

**Comment by petrkutalek** [comment]
I would suggest to use ramdisk and base64 utility:
```bash
mount -t tmpfs -o size=64m tmpfs /mnt/ramdisk
```
and then
```bash
f=/mnt/ramdisk/img
cat > ${f}.b64
base64 --decode -i ${f}.b64 -o ${f}.png
png2pos -o ${f}.bin ${f}.png
rm ${f}.png
```
