### ISSUE TITLE
Cant compile on windows with MingW

### ISSUE THREAD

**Issue by Skullcan** [petrkutalek/png2pos#7]
Hi, i'm trying to compile your application in Windows x64 and i keep getting the following error:

C:\devel\png2pos>mingw32-make -f Makefile.win strip
cc -c -std=gnu99 -O2 -Wall -pedantic -D_POSIX_C_SOURCE=200809L -D_FILE_OFFSET_BITS=64 -DLODEPNG_NO_COMPILE_ANCILLARY_CHUNKS -DLODEPNG_NO_COMPILE_CPP -DLODEPNG_NO_COMPILE_ALLOCATORS -DLODEPNG_NO_COMPILE_ENCODER -o lodepng.o lodepng.c process_begin: CreateProcess(NULL, cc -c -std=gnu99 -O2 -Wall -pedantic -D_POSIX_C_SOURCE=200809L -D_FILE_OFFSET_BITS=64 -DLODEPNG_NO_COMPILE_ANCILLARY_CHUNKS -DLODEPNG_NO_COMPILE_CPP -DLODEPNG_NO_COMPILE_ALLOCATORS -DLODEPNG_NO_COMPILE_ENCODER -o lodepng.o lodepng.c, ...) failed.
make (e=2): System couldn't find the specified file.
Makefile.win:28: recipe for target 'lodepng.o' failed
mingw32-make: *** [lodepng.o] Error 2

I've installed all the C compilers on MingW Installation.

Can you please help me? thanks!

**Comment by petrkutalek** [comment]
```
process_begin: CreateProcess(NULL, cc -c -std=gnu99 ... -o lodepng.o lodepng.c, ...) failed.
make (e=2): System couldn't find the specified file.
```
It seems this error is related to your MinGW instalation, not png2pos. mingw32-make is complaining that it cannot find compiler (cc) on your path. Please, provide me with your path (`path` command).

**Comment by Skullcan** [comment]
Hi, thx for the fast answer, my path command is pointing like this:

PATH=C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\PHP\v5.4;C:\Wind
ows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowe
rShell\v1.0\;E:\SISTEMAS\EXE\;c:\Program Files (x86)\Microsoft SQL Server\100\To
ols\Binn\;c:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;c:\Program F
iles (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program F
iles\TortoiseSVN\bin;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\Syst
em32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program
 Files\Microsoft\Web Platform Installer\;c:\Program Files (x86)\Microsoft ASP.NE
T\ASP.NET Web Pages\v1.0\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5.4 & MySQ
L Utilities 1.5.4 1.5\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5.4 & MySQL U
tilities 1.5.4 1.5\Doctrine extensions for PHP\;C:\Program Files (x86)\GitExtens
ions\;C:\Program Files (x86)\Skype\Phone\;C:\MinGW\bin

**Comment by petrkutalek** [comment]
Thank you, @Skullcan. OK, I do not have any Windows system available at the moment, will investigate your issue this evening (CEST) and will let you know.

**Comment by Skullcan** [comment]
Ok, no problem, thank you again!

**Comment by petrkutalek** [comment]
Mea culpa. I have just fixed Makefile.win. mingw32-make should call `gcc` instead of MinGW's default `cc`. You can pull latest commit or just specify compiler on command line by adding `CC=gcc`:
```
mingw32-make -f Makefile.win strip CC=gcc
```
I'm sorry for that @Skullcan.

**Comment by Skullcan** [comment]
hi, thanks again, this fixed the cc missing error. Now i'm getting other compiling error, maybe something missing in my mingw installation?

lodepng.c:1:8: error: expected '=', ',', ';', 'asm' or '__attribute__' before '/' token
 lodepng/lodepng.cpp
        ^
Makefile.win:28: recipe for target 'lodepng.o' failed
mingw32-make: *** [lodepng.o] Error 1

Thanks!

**Comment by petrkutalek** [comment]
Probably some errors with git checkout process. I have no idea what git client you use, nevertheless here is simple process how to fix it: You need 2 files from [LodePNG](https://github.com/lvandeve/lodepng) `lodepng.cpp` and `lodepng.h`. Copy those files to root folder of png2pos sources and rename `lodepng.cpp` to `lodepng.c`.

**Comment by Skullcan** [comment]
That worked! Thank you again for your time!
